Support Russian
fuyutsuki/Texter pull request #113
Opened 2021-04-08 15:02 UTC by iteplenky

This is my first language and I know how to translate correctly.

2021-04-08 15:50 UTC, fuyutsuki commented
Please refer to [en_us.ini](https://github.com/fuyutsuki/Texter/blob/release/v4.0.4/resources/language/en_us.ini) and correct the old translation.
Optionally, it would be great if you could also translate the README.md and place it as `.github/readme/ru_ru.md`.

2021-04-08 15:51 UTC, fuyutsuki requested changes

2021-04-08 15:51 UTC, fuyutsuki commented on resources/language/ru_ru.ini
> +command.txt.usage=/txt <a(dd)|e(dit)|m(ove)|r(emove)|l(ist)>
/txt list command is removed in 4.0.0

2021-04-09 04:20 UTC, iteplenky commented
> Please refer to [en_us.ini](https://github.com/fuyutsuki/Texter/blob/release/v4.0.4/resources/language/en_us.ini) and correct the old translation.
> Optionally, it would be great if you could also translate the README.md and place it as `.github/readme/ru_ru.md`.

I took en_us as a basis, and then translated it
The old translation was done entirely with google translate and some of the translations were missing.

2021-04-10 15:45 UTC, fuyutsuki commented
Even now, some translations are not compatible with 4.0. so please check.

2021-04-12 04:28 UTC, iteplenky commented
Are you sure? I mean I can't find what exactly is missing

2021-04-12 12:50 UTC, fuyutsuki commented
In the current `ru_ru.md`, there are translates that were used in 3.x but not in the 4.x (e.g. `error.config.limit.char`). Please translate them based on [the current `en_us.md`](https://github.com/fuyutsuki/Texter/blob/release/v4.0.5/resources/language/en_us.ini).

2021-04-12 12:56 UTC, fuyutsuki commented
Ah... okay, I'm sorry. You're right.
Thank you for the PR!

2021-04-12 12:56 UTC, fuyutsuki approved these changes

2021-04-12 12:58 UTC, merged